### ISSUE TITLE
M2: Releasable Component Copy-Paste with Asset Dependencies

### ISSUE THREAD

**Issue by ormsbee** [openedx/modular-learning#2]
This milestone will be built and released on edX.org.

Feedback and bug fixes from M1:
- [x] #56
- [x] #57
- [x] #58

Plus:
- [x] #16
- [x] #17
- [ ] #18
- [ ] Full release on edx.org with survey button for feedback
- [ ] Define metrics for data reporting at intervals after each milestone release
- [ ] Work out logistics for reporting bugs and communicating them
- [ ] Product support for edx.org rollout

M2 gets us to something that’s useful enough to release to end users, even if it has obvious gaps in functionality and some edge cases where it might be incompatible (e.g. content group settings).

**Comment by jmakowski1123** [comment]
Does this milestone need to be implemented in the Studio Prototype before we put it in front of testers? @bradenmacdonald

**Comment by bradenmacdonald** [comment]
I think so. A lot of this is about little details that are hard to actually evaluate other than actually implementing them in Studio. But we can test each part as it's built; we don't have to wait until the whole milestone is complete.

**Comment by bradenmacdonald** [comment]
@jmakowski1123 Could you please review the list above ^ and let me know what else is needed to consider this milestone closed out?
