### ISSUE TITLE
Epic: Edit Taxonomies in the Course Authoring MFE

### ISSUE THREAD

**Issue by bradenmacdonald** [openedx/modular-learning#239]
- [ ] #128
- [ ] #155
- [ ] Moving tags around in the editor
- [ ] #130
- [ ] Display the External ID of each tag - on the taxonomy detail page
- [ ] Display the # of times each tag has been used - on the taxonomy detail page
- [x] #132
- [x] #131
- [ ] #125
- [ ] #116
- [ ] Add "Copyright Text to Display" and "Copyright URL" to Taxonomy model and UI
- [ ] #134
- [ ] #135
- Import taxonomy tags by drag/dropping files
- [ ] #123
- [ ] #159
